# Semantic system constants matching rules.md & design.md

SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_WARNING = "WARNING"
SEVERITY_CAUTION = "CAUTION"
SEVERITY_SAFE = "SAFE"
SEVERITY_INFO = "INFO"

ROAD_STATUS_NORMAL = "NORMAL"
ROAD_STATUS_CAUTION = "CAUTION"
ROAD_STATUS_CONGESTED = "CONGESTED"
ROAD_STATUS_BLOCKED = "BLOCKED"

SHELTER_STATUS_AVAILABLE = "AVAILABLE"
SHELTER_STATUS_LIMITED = "LIMITED"
SHELTER_STATUS_NEAR_CAPACITY = "NEAR_CAPACITY"
SHELTER_STATUS_FULL = "FULL"

DEMO_MODE_BANNER = "DEMO MODE · SIMULATED DATA"
